# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
   version: 3.8
   install:
      - requirements: documentation/python_requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: documentation/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all
